# Generated by Django 2.0.3 on 2018-03-14 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_text', models.CharField(max_length=5000)),
                ('project_link', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('skill_proficiency', models.IntegerField(default=0)),
                ('skill_text', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_type', models.CharField(max_length=100)),
                ('user_age', models.IntegerField()),
                ('user_phone', models.CharField(max_length=100)),
                ('user_skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamjj.Skill')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_contributer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamjj.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_skills',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamjj.Skill'),
        ),
    ]
