# Generated by Django 2.0.3 on 2018-03-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamjj', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skill_proficiency',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_contributer',
        ),
        migrations.AddField(
            model_name='project',
            name='project_contributer',
            field=models.ManyToManyField(to='teamjj.User'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_skills',
        ),
        migrations.AddField(
            model_name='project',
            name='project_skills',
            field=models.ManyToManyField(to='teamjj.Skill'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_skills',
        ),
        migrations.AddField(
            model_name='user',
            name='user_skills',
            field=models.ManyToManyField(to='teamjj.Skill'),
        ),
    ]
