# Generated by Django 2.0.3 on 2018-03-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamjj', '0002_auto_20180314_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_profiency',
            field=models.CharField(choices=[('1', 'Freshman'), ('2', 'Sophomore'), ('3', 'Junior'), ('4', 'Senior'), ('5', 'Graduate')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
